runtime: python39

service: backend-api

# F1 is default
instance_class: F1

service_account: state-info@state-info-proj.iam.gserviceaccount.com

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
